import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Oladipupo Ibeun</title>
        <meta name="description" content="Initial Setup Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
      </main>

      
    </div>
  )
}
